services:
  - type: web
    name: trustdrive-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
